//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `DistributedSorting.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package DistributedSorting;

/** @hidden */
public class _CallbackReceiverPrxI extends com.zeroc.Ice._ObjectPrxI implements CallbackReceiverPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
